//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace VeryBigShoeCompany
{


 public partial class orderDetails
 {

  /// <summary>
  /// pnlNoItems control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
  protected global::System.Web.UI.WebControls.Panel pnlNoItems;

  /// <summary>
  /// pnlContent control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
  protected global::System.Web.UI.WebControls.Panel pnlContent;

  /// <summary>
  /// cmdPrint control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
  protected global::System.Web.UI.WebControls.Button cmdPrint;

  /// <summary>
  /// tableBody control.
  /// </summary>
  /// <remarks>
  /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
  protected global::System.Web.UI.HtmlControls.HtmlGenericControl tableBody;
 }
}
